### ISSUE TITLE
Log In page return Server Error (500)

### ISSUE THREAD

**Issue by ReggieReo** [xNatthapol/SIP#57]
When trying to access the login page, the application returns a Server Error (500).
<img width="1022" alt="Screenshot 2566-11-22 at 20 47 50" src="https://github.com/xNatthapol/SIP/assets/103312026/bc54b55f-98bc-487e-9888-0546b6263b25">

how to reproduce:
clicking the login button from any page.

**Comment by xNatthapol** [comment]
Thank you for your feedback. We've already resolved it. The login is now working.
