### ISSUE TITLE
When go to website, Show server 500

### ISSUE THREAD

**Issue by thanidacwn** [xNatthapol/SIP#62]
You have to reuse your database on heroku or kill connection in database when connection is full.

<img width="1439" alt="Screenshot 2566-11-23 at 11 05 30" src="https://github.com/xNatthapol/SIP/assets/92778351/3c51d663-fb15-40fc-9c00-7016bf9477ab">

**Comment by xNatthapol** [comment]
Thank you for your feedback. We've already fixed it.
