### ISSUE TITLE
Registration.

### ISSUE THREAD

**Issue by mjrchy** [xNatthapol/SIP#66]
I can't register for the application even though I followed all the instructions. It alerts me that the username already exists

**Comment by xNatthapol** [comment]
Thank you for your feedback. I tested the registration system and found that it works normally. The alert message that shows *"the username already exists"* means that the username is already in use. I think you should try re-registering with a different username.

**Comment by mjrchy** [comment]
I rechecked and found that the registration system is working; however,
there is no message to inform me that the registration was successful.

**Comment by xNatthapol** [comment]
I appreciate your suggestions. We will add this part if we still have time after the features.

**Comment by mjrchy** [comment]
🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️
