### ISSUE TITLE
Server 500 when try to access game page.

### ISSUE THREAD

**Issue by woraamy** [xNatthapol/SIP#74]
<img width="1512" alt="Screenshot 2566-11-26 at 10 36 49" src="https://github.com/xNatthapol/SIP/assets/113490970/334e5198-0387-406e-abcf-6b94399eb7f3">

**Comment by xNatthapol** [comment]
Thank you for reporting the bug. We've been made aware of this problem, which you can view in [issue#56](https://github.com/xNatthapol/SIP/issues/56).  
I'm sorry that you still can't use it as usual. We're trying to have it fixed as soon as possible.
